"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 19:31:27.480857
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_kind_ts', ['kind', 'ts'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_archived', ['archived'], unique=False)
        batch_op.create_index('ix_conversations_updated', ['updated_at'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind in ('ollama','openai_compatible','anthropic')", name='ck_provider_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('transcription', sa.JSON(), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('system','user','assistant','tool')", name='ck_messages_role'),
    sa.CheckConstraint("status in ('complete','streaming','cancelled','error','interrupted')", name='ck_messages_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_messages_conv_seq')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation', ['conversation_id', 'seq'], unique=False)

    op.create_table('robot_action_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('rejected','sent','completed','failed','cancelled','timeout','disconnected')", name='ck_robot_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robot_action_requests', schema=None) as batch_op:
        batch_op.create_index('ix_robot_created', ['created_at'], unique=False)

    # ### end Alembic commands ###

    # Full-text search over message content (SQLite FTS5), kept in sync by triggers.
    op.execute("CREATE VIRTUAL TABLE messages_fts USING fts5(content, message_id UNINDEXED, conversation_id UNINDEXED, tokenize='unicode61')")
    op.execute("CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN INSERT INTO messages_fts(content, message_id, conversation_id) VALUES (new.content, new.id, new.conversation_id); END")
    op.execute("CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN DELETE FROM messages_fts WHERE message_id = old.id; END")
    op.execute("CREATE TRIGGER messages_au AFTER UPDATE OF content ON messages BEGIN UPDATE messages_fts SET content = new.content WHERE message_id = old.id; END")


def downgrade() -> None:
    for t in ('messages_ai', 'messages_ad', 'messages_au'):
        op.execute(f'DROP TRIGGER IF EXISTS {t}')
    op.execute('DROP TABLE IF EXISTS messages_fts')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robot_action_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_robot_created')

    op.drop_table('robot_action_requests')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation')

    op.drop_table('messages')
    op.drop_table('provider_configs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_updated')
        batch_op.drop_index('ix_conversations_archived')

    op.drop_table('conversations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_kind_ts')

    op.drop_table('audit_events')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
